package com.lvxiao.util;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

/**
 * @author hongqi
 */
public class HtmlUtils {

    public static String getText(String html) {
        Document document = Jsoup.parse(html);
        return document.text();
    }

    public static void main(String[] args) {
        System.out.println(getText("<meta charset=\"utf-8\" />\n"
            + "<ul>\n"
            + "<li><strong><a href=\"https://www.bbc.co"
            + ".uk/learningenglish/english/features/6-minute-english_2022/ep-220428\">Remembering Desmond "
            + "Tutu</a></strong></li>\n"
            + "<li><strong><a href=\"https://www.bbc.co"
            + ".uk/learningenglish/english/features/6-minute-english_2022/ep-220421\">Discoveries of the Deep "
            + "Sea</a></strong></li>\n"
            + "<li><strong><a href=\"https://www.bbc.co"
            + ".uk/learningenglish/english/features/6-minute-english_2022/ep-220414\">Rhetoric: How persuasive are "
            + "you?</a></strong></li>\n"
            + "</ul>\n"
            + "<h3><strong>Introduction</strong></h3>\n"
            + "<p>2022 marks the 70th anniversary of Queen Elizabeth II's coronation. Neil and Sam talk about the "
            + "festivities of the Platinum Jubilee in Britain, which include a competition to choose the official "
            + "jubilee cake, the Platinum Pudding, and they teach you related vocabulary along the way.</p>\n"
            + "<h3>This week's question</h3>\n"
            + "<p>Queen Elizabeth II is Britain’s longest-ever reigning monarch, but who was the previous "
            + "longest-reigning before her?</p>\n"
            + "<p>a)    King Henry VIII<br />b)    Queen Elizabeth I<br />c)    Queen Victoria</p>\n"
            + "<p>Listen to the programme to find out the answer. </p>\n"
            + "<h3>Vocabulary</h3>\n"
            + "<p><strong>jubilee<br /></strong>celebration of the anniversary of a special event, usually associated"
            + " with the Royal Family</p>\n"
            + "<p><strong>reign<br /></strong>the period of time when a king or queen rules a country</p>\n"
            + "<p><strong>coronation<br /></strong>ceremony at which someone is made king or queen</p>\n"
            + "<p><strong>trifle<br /></strong>sweet, cold pudding made of a layer of fruit and cake, a layer of "
            + "custard, and a top layer of cream</p>\n"
            + "<p><strong>a twist on<br /></strong>a variation of a traditional food recipe, using new and exciting "
            + "ingredients or different cooking methods</p>\n"
            + "<p><strong>humble<br /></strong>modest, not proud</p>\n"
            + "<h3>Transcript</h3>\n"
            + "<p><em>Note: This is not a word-for-word transcript.</em></p>\n"
            + "<p><strong>Sam</strong><br />Hello.</p>\n"
            + "<p><strong>Neil</strong><br />Hello. This is 6 Minute English from BBC Learning English. I’m Neil.</p>\n"
            + "<p><strong>Sam<br /></strong>And I’m Sam.</p>\n"
            + "<p><strong>Neil<br /></strong>People in the UK are enjoying a four-day holiday as part of the "
            + "celebrations for Queen Elizabeth II’s Platinum Jubilee.</p>\n"
            + "<p><strong>Sam<br /></strong>A<span> </span><strong>jubilee</strong><span> </span>celebrates the "
            + "anniversary of a special event, and the word is mostly associated with the Royal Family. In 2022, "
            + "Queen Elizabeth II celebrates her Platinum Jubilee, commemorating 70 years since she became Queen in "
            + "1952.</p>\n"
            + "<p><strong>Neil<br /></strong>People are doing all kinds of things to celebrate, from large events at "
            + "Buckingham Palace and St Paul’s Cathedral, to smaller street parties in towns and cities up and down "
            + "the country, and abroad. In this programme, we look at the Platinum Jubilee in an unusual way, by "
            + "hearing about a cake competition to make the official jubilee cake - the Platinum Pudding. And, as "
            + "usual, we’ll be learning some related vocabulary as well.</p>\n"
            + "<p><strong>Sam<br /></strong>This isn’t the first celebration of Queen "
            + "Elizabeth’s<span> </span><strong>reign<span> </span></strong>– the period of time when a monarch rules"
            + " a country. In 1977, the Queen celebrated her Silver Jubilee, marking 25 years as queen, followed by "
            + "her Golden Jubilee in 2002, and her Diamond Jubilee in 2012.</p>\n"
            + "<p><strong>Neil<br /></strong>But what’s so special about this year’s Platinum Jubilee is that Queen "
            + "Elizabeth II is the first British monarch ever to spend 70 years on the throne. And I have a question "
            + "about it, Sam. Queen Elizabeth II is Britain’s longest-ever reigning monarch, but who was the previous"
            + " longest-reigning before her? Was it:</p>\n"
            + "<p>a)    Henry VIII?<br />b)    Elizabeth I?  or<br />c)    Queen Victoria?</p>\n"
            + "<p><strong>Sam<br /></strong>I know it’s c) Queen Victoria.</p>\n"
            + "<p><strong>Neil<br /></strong>OK. I’ll reveal the answer at the end of the programme. As the first "
            + "monarch ever to have a platinum jubilee, many celebrations are being planned for the Queen. These "
            + "include an official birthday parade, Trooping the Colour, which ends with jet planes flying over "
            + "Buckingham Palace, and the Platinum Pageant - a live concert in front of the palace, featuring music "
            + "and dancing, puppets of the Queen’s favourite pets - her corgi dogs - and a performance by Ed Sheeran"
            + ".</p>\n"
            + "<p><strong>Sam<br /></strong>And that’s just in London. All across the UK street parties are being "
            + "held for people to eat and drink with friends and neighbours. There’s a tradition of inventing a new "
            + "food dish to commemorate jubilees, going all the way back to the Victoria sponge, a cake named after "
            + "Queen Victoria. This year a competition was held to find a new dish to become the official pudding of "
            + "the jubilee. Here’s BBC reporter, Daniella Relph, to explain more.</p>\n"
            + "<p><strong>Daniella Relph<br /></strong>First, there was the Victoria sponge, "
            + "then<span> </span><strong>coronation<span> </span></strong>chicken, now we have a Queen Elizabeth II "
            + "Platinum Pudding. The winning lemon Swiss roll and amaretti trifle is<span> </span><strong>a twist "
            + "on</strong><span> </span>a traditional<span> </span><strong>trifle</strong>, with layers of Swiss "
            + "roll, jelly, custard, mandarins, amaretti biscuits and cream. </p>\n"
            + "<p><strong>Neil<br /></strong>In 1953, a mix of chicken and curry cream sauce called, coronation "
            + "chicken, was invented to celebrate Queen "
            + "Elizabeth’s<strong><span> </span>coronation</strong><span> </span>– the ceremony at which she was made"
            + " queen.</p>\n"
            + "<p><strong>Sam<br /></strong>This year, competition winner, Jemma Melvin, has invented a lemon and "
            + "Swiss roll amaretti trifle as the official jubilee cake"
            + ".<strong><span> </span>Trifle<span> </span></strong>is a sweet, cold pudding made of three layers – a "
            + "layer of fruit and cake, a layer of custard, and a top layer of cream.</p>\n"
            + "<p><strong>Neil<br /></strong>Jemma’s jubilee trifle is<span> </span><strong>a twist "
            + "on</strong><span> </span>a traditional trifle. When talking about food, people use the "
            + "phrase<span> </span><strong>a twist on</strong><span> </span>something to describe a new variation of "
            + "a traditional recipe, using different, exciting ingredients.</p>\n"
            + "<p><strong>Sam<br /></strong>Jemma learned her winning recipe from her grandmothers. She wants her "
            + "trifle to be “the people’s pudding”, something to be enjoyed by everyone. Here is Jemma Melvin "
            + "describing how she felt to discover her trifle had been chosen as the official Platinum Pudding:</p>\n"
            + "<p><strong>Jemma Melvin<br /></strong>I cannot believe it! Everything that I was up against was just "
            + "the most beautiful desserts and pudding with beautiful stories. (That) this "
            + "quite<span> </span><strong>humble</strong><span> </span>trifle has won is a bit surreal.</p>\n"
            + "<p><strong>Sam<br /></strong>Jemma describes her trifle "
            + "as<span> </span><strong>humble</strong><span> </span>– modest, and not proud. Although the pudding "
            + "contains ingredients like amaretti biscuits and cream, which are good enough for a queen, she wanted "
            + "to base it on a humble trifle, something everyone around the country can make.</p>\n"
            + "<p><strong>Neil<br /></strong>Enjoying a bowl of Jemma’s Platinum Pudding sounds like a great way for "
            + "some to celebrate the Queen’s seventy-year reign.</p>\n"
            + "<p><strong>Sam<br /></strong>Which reminds me of your question, Neil. We know Elizabeth II has reigned"
            + " for 70 years, but who was the second longest-serving monarch? I said it was c) Queen Victoria.</p>\n"
            + "<p><strong>Neil<br /></strong>I’m glad you were so sure, because you were correct, Sam. Victoria was "
            + "queen for almost 64 years which is a long time, but not as long as Elizabeth.</p>\n"
            + "<p><strong>Sam<br /></strong>OK, let’s recap the vocabulary from this programme about the "
            + "Queen’s<span> </span><strong>jubilee<span> </span></strong>– a celebration of the anniversary of a "
            + "special event, usually involving the Royal Family.</p>\n"
            + "<p><strong>Neil<br /></strong>A king or queen’s<span> </span><strong>reign<span> </span></strong>means"
            + " the period of time they rule a country.</p>\n"
            + "<p><strong>Sam<br /></strong>A<strong><span> </span>coronation<span> </span></strong>is the ceremony "
            + "at which someone is made monarch – the king or queen.</p>\n"
            + "<p><strong>Neil<br /></strong><strong>Trifle<span> </span></strong>is a popular pudding made of a "
            + "layer of fruit and cake, a layer of custard, and a top layer of cream.</p>\n"
            + "<p><strong>Sam<br /></strong>If you say a food dish is<span> </span><strong>a twist "
            + "on<span> </span></strong>something, you mean it’s a variation of a traditional recipe, using new and "
            + "exciting ingredients.</p>\n"
            + "<p><strong>Neil<br /></strong>And finally, someone who "
            + "is<span> </span><strong>humble<span> </span></strong>is modest, and not proud.</p>\n"
            + "<p><strong>Sam<br /></strong>If you were inspired by this recipe, why not try making it. But that’s "
            + "all from us. Goodbye for now. </p>\n"
            + "<p><strong>Neil<br /></strong>Goodbye!</p>"));
    }
}
