#spring:
#  cache:
#    caffeine:
#      spec: initialCapacity=10,maximumSize=200,expireAfterWrite=30s
#    type: caffeine
debug: true
example:
  service:
    enabled: true
    prefix: 我是一个前缀
    suffix: 我是一个后缀